version: '3.9'
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"

services:
    prometh-app:
        image: nginx
        ports:
            - "8080:9001"
        volumes:
            - ./prometheus:/usr/share/nginx/html
        networks:
            app_net:
                ipv4_address: 172.16.238.10
    otel:
        image: otel/opentelemetry-collector:0.25.0
        volumes:
            - ./otel:/etc/otel-conf
        command: --config /etc/otel-conf/otel-prometheus-scapper.yaml
        networks:
            - app_net
